### PR TITLE
fix set_field actions

### PR DESCRIPTION
**Pull request by hkwi**

### CODE REVIEW

**Comment by gizmoguy** [comment]
This change seems to break pushing (single tagged) VLANs for me.

I have a flow that looks like:

`Flow 13
 Match:
  In Port: 1
 Attributes:
  Table ID: 0                           Cookie:0x5adc15c0
  Priority: 9000                                Duration: 661 secs
  Byte Count: 23580                     Packet Count: 393
  Last Match: 00:00:01
 Instructions:
  Apply Actions:
   Push VLAN tag
   Set VLAN ID: 100
  Goto Table: 2`

However when that gets applied to a packet:

> Looking for match in table 0 from port 1 : 52:54:00:FF:B2:66 -> FF:FF:FF:FF:FF:FF eth type 0806
> Matched flow 13, table 0
> Set VID 4196
> Goto table 2

VLAN 4196 is 0x1064, which is VLAN 100 (0x64) with the OFPVID_PRESENT bit set, are you remembering to mask that off correctly?

**Comment by gizmoguy** [comment]
Also there is a rebase required on this commit as it removes push_vlan_helper and pop_vlan_helper methods that were added in a VLAN rework by @anarkiwi in PR #23 which is already merged.

**Comment by pzanna** [comment]
Unable to apply the PR at this time, will discuss changes for next version.

**Comment by hkwi** [comment]
So then please cut a new branch.

**Pull request closed without merging**
